baseURL: https://brett.cloud
languageCode: en-us
title: brett.cloud
params:
  author:
    name: Brett Gardiner
    email: hi@[domain]
  description: Brett in the cloud ⛅️
  postTypes:
    - post
    - link
cascade:
  layout: single
  comments: false

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml
  application/json:
    suffixes:
      - json
outputFormats:
  Atom:
    name: Atom
    mediaType: application/atom+xml
    baseName: atom
    isPlainText: false
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false
  RSS:
    baseName: rss
  JSON:
    name: Json
    mediaType: application/json
    baseName: feed
    isPlainText: true
    # suffix: json
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false

outputs:
  home: [HTML, RSS, Atom, JSON]

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

module:
  mounts:
    - source: static
      target: static
    - source: ./node_modules/typeface-fira-code/files/
      target: static/styles/files/
    - source: ./node_modules/typeface-patua-one/files/
      target: static/styles/files/
    - source: ./node_modules/typeface-roboto-slab/files/
      target: static/styles/files/
    - source: ./node_modules/mermaid/dist/mermaid.min.js
      target: static/scripts/mermaid.min.js
