baseURL: https://brett.cloud
languageCode: en-us
title: brett
cascade:
  layout: single
  comments: false

module:
  mounts:
    - source: static
      target: static
    - source: ./node_modules/typeface-fira-code/files/
      target: static/styles/files/
    - source: ./node_modules/typeface-patua-one/files/
      target: static/styles/files/
    - source: ./node_modules/typeface-roboto-slab/files/
      target: static/styles/files/
    - source: ./node_modules/mermaid/dist/mermaid.min.js
      target: static/scripts/mermaid.min.js
