---
version: '3'

vars:
  PROJECT_DIR:
    sh: git rev-parse --show-toplevel

env:
  ROOT_DIR: '{{.PROJECT_DIR}}'

includes:
  lint: .taskfiles/lint.yaml
  precommit: .taskfiles/precommit.yaml
  setup: .taskfiles/setup_{{OS}}.yaml

tasks:
  default:
    silent: true
    cmds:
      - task -l

  init:
    desc: Install dependencies and setup environment
    cmds:
      - task: setup:init
      - task: precommit:init
      - task: precommit:update
      - task: npm-install

  start:
    desc: Run development server
    cmds:
      - hugo server --navigateToChanged --gc

  build:
    desc: Build production static site
    cmds:
      - hugo

  npm-install:
    cmds:
      - npm install
    status:
      - test -d node_modules

  create-envrc:
    desc: Create local environment variable file
    cmds:
      - cp example.envrc .envrc
    status:
      - test -f .envrc

  python:
    desc: Install python dependencies
    cmds:
      - |
        ([ "{{.CLI_ARGS}}" == "force" ] || pip -V 2>/dev/null | grep -q .virtualenv) && \
            pip install -r requirements.txt || \
            echo "You may want to activate a python virtual environment before installing the python dependencies.
        Pass 'force' as argument to continue anyway (e.g. task python -- force)."
    silent: true
