export const theme = {
  themeLighterAlt: "#f6fbff",
  themeLighter: "#daedff",
  themeLight: "#b9ddff",
  themeTertiary: "#74bcff",
  themeSecondary: "#339cff",
  themePrimary: "#1890ff",
  themeDarkAlt: "#1581e6",
  themeDark: "#116dc2",
  themeDarker: "#0d508f",

  neutralLighterAlt: "#f8f8f8",
  neutralLighter: "#f4f4f4",
  neutralLight: "#eaeaea",
  neutralQuaternaryAlt: "#dadada",
  neutralQuaternary: "#d0d0d0",
  neutralTertiaryAlt: "#c8c8c8",
  neutralTertiary: "#c2c2c2",
  neutralSecondary: "#858585",
  neutralPrimaryAlt: "#4b4b4b",
  neutralPrimary: "#333333",
  neutralDark: "#272727",

  black: "#1d1d1d",
  white: "#ffffff",

  red: "#e81123",
  redDark: "#a80000",

  green: "#bad80a",
  greenDark: "#107c10",
}

export const themeInverted = ({
  themeLighterAlt,
  themeLighter,
  themeLight,
  themeTertiary,
  themeSecondary,
  themePrimary,
  themeDarkAlt,
  themeDark,
  themeDarker,
  neutralLighterAlt,
  neutralLighter,
  neutralLight,
  neutralQuaternaryAlt,
  neutralQuaternary,
  neutralTertiaryAlt,
  neutralTertiary,
  neutralSecondary,
  neutralPrimaryAlt,
  neutralPrimary,
  neutralDark,
  black,
  white,
  red,
  redDark,
  green,
  greenDark,
}) => ({
  themeLighterAlt: themeDarker,
  themeLighter: themeDark,
  themeLight: themeDarkAlt,
  themeTertiary: themePrimary,
  themeSecondary: themeSecondary,
  themePrimary: themeTertiary,
  themeDarkAlt: themeLight,
  themeDark: themeLighter,
  themeDarker: themeLighterAlt,
  neutralLighterAlt: neutralDark,
  neutralLighter: neutralPrimary,
  neutralLight: neutralPrimaryAlt,
  neutralQuaternaryAlt: neutralSecondary,
  neutralQuaternary: neutralTertiary,
  neutralTertiaryAlt: neutralTertiaryAlt,
  neutralTertiary: neutralQuaternary,
  neutralSecondary: neutralQuaternaryAlt,
  neutralPrimaryAlt: neutralLight,
  neutralPrimary: neutralLighter,
  neutralDark: neutralLighterAlt,
  black: white,
  white: black,
  red: redDark,
  redDark: red,
  green: greenDark,
  greenDark: green,
})
