name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    # api: https://developer.github.com/webhooks/event-payloads/
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: true

      # New syntax for setting environment variables:
      # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
      - name: Set build version & time
        run: |
          echo "HUGO_BUILD_VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "HUGO_BUILD_TIME=$(date --iso-8601=seconds)" >> $GITHUB_ENV

      - name: Build
        run: hugo --minify
        env:
          NODE_ENV: production

      # source: https://github.com/tschaub/gh-pages/issues/345#issuecomment-608243163
      - name: Deploy site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d public -u "$GITHUB_ACTOR@users.noreply.github.com" -m "deploy revision $HUGO_BUILD_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
